### ISSUE TITLE
wrong file name

### ISSUE THREAD

**Issue by rpoleski** [valboz/RTModel#4]
I've installed RTModel on linux. When I run it, it fails in `RTModel.py` line 76 with message:
```
FileNotFoundError: [Errno 2] No such file or directory: '/.../.local/lib/python3.8/site-packages/RTModel/bin/Reader'
```

In that directory there is `Reader.exe`, not `Reader`. I guess other linux users will have similar issue. @golmschenk, @valboz, can you help?

**Comment by valboz** [comment]
Hi Radek, have you tried the GitHub installation or the PyPI? 
The GitHub should be more robust against different operating systems.
Which Linux setup are you using?

**Comment by rpoleski** [comment]
I've tried PyPI on a machine with Rocky Linux 8.7.

I've tried github as well, but that one fails on installation in [line 369 of LevMarFit.cpp](https://github.com/valboz/RTModel/blob/44d621dca296938b49f24e932678ad2c20cbd97b/RTModel/lib/LevMarFit.cpp#L369):

```c
	if (incond >= ninit) nps=nps/0;
```

**Comment by valboz** [comment]
This looks like a linking issue. I leave it to @golmschenk .

**Comment by golmschenk** [comment]
Sorry for the delay. The issue is that GCC 8 is a bit old and does not link to the part of the C++ standard library for the filesystem by default (GCC 9 or greater does), and RTModel expects this part of the standard library to be available.

@rpoleski, a quick workaround (which I don't have an immediate way to test on my end) would be to tell the build process to link this library during the build. I think this could be done by adding some linking flags to the build. So the updated `pip` command that installs from the git repository, but also attempts to link the library would be `pip install git+https://github.com/valboz/RTModel --config-settings=cmake.args=-DCMAKE_EXE_LINKER_FLAGS=-lstdc++fs`. However, assuming that part works, there still may be other libraries that are not linked by default in GCC 8 that might cause more issues). But this, is the quick easy thing to try.

Probably the better approach would be to use an updated version of GCC. My recommended way to do this would be to use a Conda environment, where you can install an updated compiler, but, since it will be in a separate environment, it won't mess with your global system compilers. To do this, you'll first need a version of Conda installed (most people already have this nowadays, but if you don't, miniforge is a good option: https://github.com/conda-forge/miniforge?tab=readme-ov-file#download). Once installed, you create a new environment (e.g., `conda create -n rtmodel_env python=3.11`). Activate the environment (`conda activate rtmodel_env`). Install the compilers (`conda install -c conda-forge cxx-compiler` and `conda install -c conda-forge c-compiler`). Then you can install RTModel (`pip install git+https://github.com/valboz/RTModel`). There are many other approaches to updating the compilers as well, but approach has a minimal impact on other projects you have.

@valboz, as for a real fix, there are a couple options. One is simply to disallow users from using older versions of GCC. The other is to have CMake automatically detect the filesystem library when needed, though this will clutter the CMakeLists.txt build script a bit more. Let me know what you think is preferable.

**Comment by valboz** [comment]
Thanks @golmschenk . Indeed the STL is quite essential in RTModel and I believe it is going to become essential for future codes in general. So I think it makes no point in supporting old versions of gcc that do not link it.
@rpoleski do you have any particular reason for not updating your gcc?

**Comment by rpoleski** [comment]
Instalation works for me now. Thanks.

> @rpoleski do you have any particular reason for not updating your gcc?

I haven't written that I don't want to update gcc.
